### PR TITLE
Clean up repo

### PR DESCRIPTION
**Pull request by mcaceresb**
The branch cleans up the repo so it can be submitted to CRAN (passes `R CMD check --as-cran`). Changes are:

- Packages:
    - Delete library statements from all R files (deprecated by #26)
    - Added matrixStat, deleted ROI
- Docs:
    - Updated man files to match function definitions.
    - Renamed doc folder to vignettes
- Description:
    - Bumped version # to 0.2.3
    - Added VignetteBuilder and knitr
    - Set Ashesh's e-mail to ashesh.a.rambachan@gmail.com
    - Changed https://jonathandroth.github.io to https://www.jonathandroth.com/
    - Changed title to Title Case
- See commit notes in 918c5278c9897fc079a3bc69c8e98ee75ffcc65d for more details

@asheshrambachan @jonathandroth  **Questions**

- When I run the CRAN checks I get this note: `Namespace in Imports field not imported from: ‘doParallel’`. It might be ignorable, but I'm trying to figure out where doParallel is used. Does it import %do%? Is it a back-end for foreach? I don't have experience with doParallel, sorry if it's meant to be clear!

- Several files in `man` have placeholders for keywords. How to fill them?

### CODE REVIEW

**Comment by jonathandroth** [comment]
@Ashesh Rambachan ***@***.***> any idea on how %do% is
being used here?

**Comment by asheshrambachan** [comment]
`%do%` is loaded in the `foreach` which I think gets used to loop over alternative values of `M` or `Mbar` in the sensitivity analysis results functions.  `doParallel` was how we originally implemented parallelized versions via `%dopar%`.

**Comment by mcaceresb** [comment]
@asheshrambachan @jonathandroth Since both are imported from foreach I'll just make doParallel a suggested package instead of required.

I'll also delete the placeholder keywords for now. So if there's nothing else I'll implement those changes and merge the PR tomorrow (traveling rn). After that it should be set for CRAN (unless you want to add tests).

**Comment by mcaceresb** [comment]
@asheshrambachan @jonathandroth Done! I also updated the manual (`doc/manual.pdf`) but `devtools`/`R CMD` tell me that it's not standard to include a `doc` directory. I tried looking around and I'm not sure where else to put the manual, however.

**Comment by jonathandroth** [comment]
Just wanted to follow up on the status of preparing this for CRAN. Is the package ready to go to CRAN? Or is there something we're waiting on? If it's ready, we should submit it!

**Comment by mcaceresb** [comment]
It should be ready.

**Comment by mcaceresb** [comment]
@jonathandroth Just checking in in case you were waiting for me? I believe Ashesh has to submit  the package, tho. See [here](https://cran.r-project.org/submit.html).

`devtools::build()` should make the requisite `.tar.gz` file that he'll have to upload.

**Comment by asheshrambachan** [comment]
Thanks @mcaceresb! I didn't realize I had to submit the package. I'll do it this weekend and let you know if I run into any issues.

**Comment by mcaceresb** [comment]
@asheshrambachan I haven't submitted a CRAN package before. It looks to me that the package maintainer has to submit  but if that wasn't the case LMK for future reference.

**Comment by jonathandroth** [comment]
Did you submit this Ashesh?

**Comment by jonathandroth** [comment]
?

**Comment by asheshrambachan** [comment]
Thanks for the reminder! 

I started the process of submitting the package. As part of the submission, we have to run some checks to see if there any "bad practices" in the package's implementation -- this just involves running `devtools::build()` or `R CMD check --as-cran` after building the `.tar.gz' file.  My understanding of the [CRAN policy](https://cran.r-project.org/web/packages/policies.html) is that we have to address all notes raised by this check.

@mcaceresb when I ran this check, I got the following three notes in the screenshot below: 
Screenshot 2023-07-17 at 6 09 29 PM
Do you know how to fix these notes? 

The CRAN policy also says "If there are warnings or notes you cannot eliminate (for example because you believe them to be spurious) send an explanatory note as part of your covering email, or as a comment on the submission form." So if we can't fix them, then we can just include an explanatory note in the comment on the submission.

**Comment by mcaceresb** [comment]
@asheshrambachan  Right so let's take these issues in turn:

1. `doParallel`: I thought this was fixed, so I'm not sure what it's about.  I also don't get this error locally, and it seems it might be an OS-specific thing. I can just get rid of `doParallel` as a suggested package? LMK
2.  `doc`: This contains the manual. I'm not sure if you've linked to it ever, but apparently `doc` is not supposed to be a directory included in the package submission. If you're good I can just delete it. LMK.
3. `no visible binding`: `dplyr` refers to variables in context, so all those variables don't exist, so R, complains, but the code runs because dplyr looks for them inside the data. I don't know how to fix those notes, but the package should run (because dplyr is working correctly).

**Comment by asheshrambachan** [comment]
Thanks @mcaceresb! On the issues:

1. Yes, I think it's easiest to just get rid of `doParallel` as the suggested package at this point.
2. Yes, let's go ahead and delete the manual. We never really directed users towards it, and I think we can safely remove given the detailed vignette we now have.
3. Got it -- that makes sense. Per my post [here](https://github.com/asheshrambachan/HonestDiD/pull/30#issuecomment-1638954706), we can provide an explanatory note with the submission so I can mention that we are aware of this note and it does not affect the running of the package.

Let me know when you made those two changes and I will submit!

**Comment by jonathandroth** [comment]
Fantastic, thank you both!

**Comment by mcaceresb** [comment]
@asheshrambachan Done in #35; LMK if it fixes the issues.

**Comment by asheshrambachan** [comment]
Thanks @mcaceresb! I think the issues are fixed. The only one that remains is the `no visible binding:dplyr` but I'll include a note with the submission.

It looks like the CRAN submissions are offline until Aug 7th due to maintenance work (see screenshot). I'll come back and submit the package when it's back online.

Screenshot 2023-07-22 at 11 53 36 AM

**Comment by jonathandroth** [comment]
Good thing you don't have anything going on between now and Aug 7, Ashesh :)

**Comment by asheshrambachan** [comment]
Submitted this morning! Let's see what happens. 
Screenshot 2023-08-14 at 8 23 56 AM

**Comment by jonathandroth** [comment]
Word, thanks!

**Comment by asheshrambachan** [comment]
@mcaceresb the CRAN maintainers say we need to address the `no visible binding:dplyr` note from the build check. They wrote me this email below: 
Screenshot 2023-08-14 at 9 16 53 AM

**Comment by mcaceresb** [comment]
Addressed in #40.

**Comment by asheshrambachan** [comment]
Thanks @mcaceresb!

Resubmitted to CRAN. 
Screenshot 2023-08-24 at 7 52 34 PM

**Comment by jonathandroth** [comment]
Thanks both!

**Comment by asheshrambachan** [comment]
Got the following feedback from CRAN. Nothing seems like it would be major to fix. 
Screenshot 2023-08-31 at 4 07 26 PM

**Comment by jonathandroth** [comment]
Boy, they are sticklers!

Mauricio, might you have some RA time this semester to do the final
clean-up on this?

**Comment by mcaceresb** [comment]
@jonathandroth @asheshrambachan I should be able to get to this next week when the semester starts.

I have no idea what the first one means,  but hopefully it ends up being documented somewhere. The rest I understand (though they seem to be using some type of linter; they ought to just make that part of the submission process I think instead of manual back and forth).

Anyway, I take it you don't have very strong feelings about what examples I give in the .Rd files?

**Comment by jonathandroth** [comment]
Sounds great, thanks Mauricio!

**Comment by mcaceresb** [comment]
@jonathandroth @asheshrambachan I started to answer everything [here](https://github.com/asheshrambachan/HonestDiD/pull/30#issuecomment-1701712596) in #42. Just need to add examples to each .Rd file.

In the meantime:

- Can you check the description [here](https://github.com/asheshrambachan/HonestDiD/blob/c795623af9a60a752edfa7ca3af12b62791d4210/man/constructOriginalCS.Rd#L37-L50) is OK?
- I gave both of you author and copyright and Ashesh maintainer in the Authors@R field. If there's a different configuration I should use LMK.

**Comment by jonathandroth** [comment]
Both look fine to me!

**Pull request merged**
