### PR TITLE
Updated readme with unified example 

### PR DESCRIPTION
**Pull request by jonathandroth**

### CODE REVIEW

**Comment by asheshrambachan** [comment]
Thanks! This looks overall great to me.

Some small comments below based on the compiled readme over [here](https://github.com/jonathandroth/HonestDiDCopy#honestdid).

1. For some reason, \bar{M} is typeset oddly throughout (see screenshot). Perhaps \overline{M} will typeset better?
Screen Shot 2022-09-14 at 4 18 06 PM
2. Under ``robust confidence intervals,'' should it be: these confidence intervals account for the fact that there is estimation _error_ both in the treatment effects estimates and our estimates of the pre-trends. 
3. At the beginning of the example usage section, we should say in text that we got this example from Scott Cunningham's Causal Mixtape book.
4. Should we explicitly say in the text that we use the `did` package to estimate the event-study specification (with a link to the package.)? I also think in the code snippets, we should use the convention `package_name::function` so that its clear what functions come from which package. Obviously not necessary for utilities like `here`, `dplyr`, `ggplot2` but would be good for `did`, `fixest`, and `haven.` Doing so would make it as clear as possible about what comes from where to someone who may not be super familiar with `R.` (although the stata package makes this less necessary).
5. Under `Sensitivity analysis using relative magnitudes restrictions,' is it worth doing some more hand-holding through what each input to the function means? I think for numPrePeriods, numPostPeriods etc the comments in the snippet are sufficient, but l_vec may not be as obvious. 
7. It would be easier to read if you formatted functions using `code` text as opposed to italics -- e.g., see screenshot. 
Screen Shot 2022-09-14 at 4 29 42 PM
8. The code snippet under "Sensitivity Analysis Using Smoothness Restrictions" doesn't input l_vec. Should we mention it specifies a default?

**Comment by jonathandroth** [comment]
Thanks for the comments!

Re 1), hmmm. Github only recently implemented Latex support and it's kinda
buggy. The Mbar shows up fine when I compile locally. Unfortunately,
\overline{M} does not appear to be supported in Markdown. As a hack, I
replaced the Mbar equations with links to images of the equations generated
by https://latex.codecogs.com/. I also replaced the TWFE equation in this
way because it was displaying weird.

Re 2), yes, fixed.

Re 3) -- this is not from Scott's book. It is an example I came up with
when I did a lecture as part of his "Mixtape sessions" lecture series.
(Based on an example from Bacon, but I don't think we need to cite him.)

Re 4), I've added in explicit package references. We do say that we use the
did package, and I added a link to it.

Re 5) and 7), I agree that the previous usage of l_vec was confusing.
Since the default is to use the first period, I have removed l_vec from the
examples you mentioned. I then added a more detailed explanation of l_vec
in the section where we do average effects.

Re 6), I have fixed this.

I have also added a section at the end with a link to the old vignette that
discusses additional features, and to a youtube video of a talk I gave
about this.

**Comment by asheshrambachan** [comment]
Awesome! 

Re 3) Ah got it. I saw the data was being pulled from the causal mixtape, so didn't know if that was an example in his book!

One final thing:

8) Under ``Sensitivity Analysis Using Smoothness Restrictions,'' you added the example `l_vec = basisVector(3, numPostPeriods).` Should we just switch it to `basisVector(2, numPostPeriods)` since there are only two post periods in the example?

Aside from that, these fixes look good to me and I'll merge in the pull request.

**Comment by jonathandroth** [comment]
Sounds good - I have updated that example. Think we're good to merge.

**Pull request merged**
