### PR TITLE
Pull Request follow-up for #30: Reset radom seed

### PR DESCRIPTION
**Pull request by mcaceresb**

### CODE REVIEW

**Comment by mcaceresb** [comment]
@jonathandroth I reset the random seed here after the function's run, which was an easy mod. I can also not set the random seed internally and instead modify the code to use something like halton sequences? I wonder if CRAN will complain about a function fiddling with the global environment at all.

**Comment by jonathandroth** [comment]
In the past i have had an argument to the function `seed =0` and done
set.seed(seed).

I think I did this in the staggered package, which they approved. But maybe
I just got lucky that they didn't notice it

**Comment by mcaceresb** [comment]
@jonathandroth I'm not sure it's luck because the same thing happens in one function here that they also didn't flag. So I think if we put it in an argument they won't complain.

However, if the argument is not user-accessible then it has the same effect, we're just hiding it from them and going against their best practices. I guess I could make the seed user-accessible and pass it around throughout?

**Comment by jonathandroth** [comment]
If it's not a lot of work to allow the user to set it, then sure. If it is,
let's just make it an argument internally

**Comment by mcaceresb** [comment]
@jonathandroth I made the seed user-accessible. I see the PR branch is passing all checks so if you're good I'll merge to main and reply in #42

**Comment by jonathandroth** [comment]
Sounds good to me, thanks!

**Pull request merged**
