### PR TITLE
PR for Base Unit Tests and CI

### PR DESCRIPTION
**Pull request by mcaceresb**
@jonathandroth Implemented basic tests checking all the options run without error. This revealed one bug (typo) and some (very) minor unaddressed warnings.

### CODE REVIEW

**Comment by jonathandroth** [comment]
Thanks! Looks like we fixed the same typo :) If you resolve the merge conflict, should be good to go.

**Comment by mcaceresb** [comment]
@jonathandroth The merge conflict appeared to just be whitespace. Cheers!

**Comment by jonathandroth** [comment]
And whose version of the whitespace did you accept ;-)

**Comment by mcaceresb** [comment]
@jonathandroth I'm actually not sure!

I usually take out trailing whitespace, which I can defend to an extent, but if it was tabs vs spaces I don't want to accidentally start a war.

**Pull request merged**
