### PR TITLE
Pull Request follow-up for #30: Various minor fixes

### PR DESCRIPTION
**Pull request by mcaceresb**
This addresses 5 of the 6 requests [here](https://github.com/asheshrambachan/HonestDiD/pull/30#issuecomment-1701712596).

Done:

- [X] Replaced author and maintainer fields with Authors@R; gave both Ashesh and Jon author and copyright and Ashesh creator/maintainer
- [X] Removed all standardtext from .Rd files (e.g. placeholder comments in main/basisVector.R)
- [X] Changed all T/F to TRUE/FALSE
- [X] Closed [ in DESCRIPTION
- [X] Added return value to man/constructOriginalCS.Rd

Pending:

- [x] Add executable examples to each doc file; e.g.

```
\examples{
  foo(bar)
}
```

### CODE REVIEW

**Comment by mcaceresb** [comment]
@asheshrambachan @jonathandroth I added a _very_ simple example for several functions (though not stuff that seemed to mainly be used internally like `computeConditionalCS*`).

I figured it'd be redundant to make longer examples in light of the vignette, so I wrote a comment in each directing people there. If that sounds fine then I can merge into master and you can try again.

**Comment by jonathandroth** [comment]
Thanks, Mauricio! Having simple examples seems good to me.

One Q: is it obvious that if we say "See vignette" that ppl know to go to
the examples on the Github page? Should we maybe a more explicit link?

**Comment by mcaceresb** [comment]
@jonathandroth I changed all of them so they reference the name of the vignette, so they all prompt the user to call `vignette("HonestDiD_Example")`

**Comment by jonathandroth** [comment]
And vignette("HonestDiD_Example") links to what exactly?

**Comment by mcaceresb** [comment]
@jonathandroth It opens the vignette. For pdf documents it opens it in the pdf viewer specified by `getOption("pdfviewer")`; for html documents it opens it in the HTML viewer specified by `getOption("browser")`. Not sure if `pdfviewer` and `browser` are set by default (they weren't for me and I had to set them manually in my console; though the default HTML viewer in R-studio is just it's side pane, which is the one used to open html help for regular functions).

I've found references to `vignette("name")` in several packages so I figured it was convention. LMK if it sounds OK. (Though I get the impression referencing HTML vignettes is more common; maybe because people don't have to set an HTML viewer in an IDE but they have to set a pdfviewer either way?)

**Comment by jonathandroth** [comment]
Thanks. Is the vignette distinct from the README on the github page? It
seems like the README is where we want to send people?

**Comment by mcaceresb** [comment]
@jonathandroth How about

```
for more detailed examples, see <https://github.com/asheshrambachan/HonestDiD>
```

?

**Comment by jonathandroth** [comment]
Great! (Maybe make it https://github.com/asheshrambachan/HonestDiD#honestdid
)

**Comment by mcaceresb** [comment]
@jonathandroth @asheshrambachan I think we're good to try again. All the points [here](https://github.com/asheshrambachan/HonestDiD/pull/30#issuecomment-1701712596) were addressed. Apologies for the delay.

**Comment by jonathandroth** [comment]
Thanks @mcaceresb ! @asheshrambachan, let us know when you hear back from CRAN!

**Comment by jonathandroth** [comment]
@asheshrambachan any luck submitting this to CRAN ?

**Comment by mcaceresb** [comment]
@jonathandroth @asheshrambachan Checking in on the CRAN status?

**Comment by asheshrambachan** [comment]
Resubmitted to CRAN today. I'll let you know if we get back any things to fix. 
Screenshot 2024-02-23 at 3 52 47 PM

**Comment by jonathandroth** [comment]
Thanks Ashesh!

**Comment by asheshrambachan** [comment]
We received the following response on the CRAN submission. It looks like overall some issues with the documentation, and we have to fix them before resubmitting.
[CRAN_Submission.pdf](https://github.com/asheshrambachan/HonestDiD/files/14393795/CRAN_Submission.pdf)

**Comment by mcaceresb** [comment]
@asheshrambachan @jonathandroth On the five notes:

1. Rambachan and RESTUD are not misspelled, so ignore.
2. `.github` shouldn't be included in the final folder. Was this my error? LMK where you got the file you uploaded.
3. There's a set of notes noting `Delta^{SD}(M)` and similar LaTeX-style parts of the descriptions need an escape. I'll look around about how to do that because I'm not sure.
4. Some lines are too long; fixed.
5. Apparently some examples take a while to execute, but that's just how the function is. I could make the grid small for the examples, though? LMK.

**Comment by jonathandroth** [comment]
Thanks, Mauricio!

Re 3: if it's hard to figure out, I think it's fine to just
write DeltaSD(M) instead of Delta^{SD}.
Re 5: seems fine with me to make the grid smaller.

If those are fixed, it seems the only thing remaining is to ensure that the
file we upload does not have .github in it.

**Comment by mcaceresb** [comment]
@jonathandroth @asheshrambachan Ok, we should be good for another round. Notes

1. Noted
2. Added `.github` to `.Rbuildignore`
3. Enclosed all math in `\eqn{...}`
4. Fixed long lines
5. Made examples run faster by asking for a coarser grid.

See #54 for the merge.

**Comment by jonathandroth** [comment]
Thanks Mauricio! @Ashesh Rambachan ***@***.***>, could
you try resubmitting this when you have the chance? If I'm not mistaken, I
think you need to remove the .git directory before submitting?

J

**Comment by mcaceresb** [comment]
@asheshrambachan @jonathandroth On the `.github`, I added it to [`.Rbuildignore`](https://github.com/asheshrambachan/HonestDiD/blob/master/.Rbuildignore#L6) so I think we should be fine there.

**Comment by asheshrambachan** [comment]
@jonathandroth @mcaceresb CRAN took some time to respond (they continued to flag the spelling of RESTUD and my name so I had to email and wait for a manual response). Those are fine, but they are still saying that our tests are too slow (see the attached screenshot).

Perhaps, for the tests, we could precompute the sensitivity analyses and so the tests are just the plotting functions? Or we could really scale down the grid sizes. 
Screenshot 2024-04-16 at 9 54 30 AM

**Comment by jonathandroth** [comment]
Thanks, Ashesh! Maybe let's try to doing the example with a grid resolution
of say 10 instead of 1000 (and make a code comment that this is just for
execution time).

**Comment by mcaceresb** [comment]
@jonathandroth What do I do with the vignette?

**Comment by jonathandroth** [comment]
Is the vignette just a copy-paste of the README on the Github? Maybe we
should just replace the Vignette with "See the README at <URL>". Or
alternatively, maybe there's an option to not evaluate the results of the
vignette and just have those saved?

**Comment by jonathandroth** [comment]
@mcaceresb just wanted to follow up on this - thanks!

**Comment by mcaceresb** [comment]
@jonathandroth @asheshrambachan Can try again. Please double-check the README and vignette before doing so. Summary in #56; see [here](https://github.com/asheshrambachan/HonestDiD/pull/56#issue-2267690355).

**Comment by jonathandroth** [comment]
Thanks so much, Mauricio!

One Q: are we required to include this PDF vignette? The PDF you referenced
appears to be somewhat out of date anyway, and since we've spent a lot of
time on the README on the Github page, I wonder if we should just point
users there?

**Comment by mcaceresb** [comment]
@jonathandroth I'm not sure if a vignette is required. Should I delete and see if they say anything?

**Comment by jonathandroth** [comment]
I don't see anything on the CRAN website indicating a vignette is required.
Can you just try running the check() function in devtools without it. If it
doesn't flag this, let's just delete the PDF vignette and point people to
the Github README in the package documentation.

J

**Comment by mcaceresb** [comment]
@jonathandroth I'm deleting this from the README, then?

```
See the previous package [vignette] for additional examples and package options, including incorporating sign and monotonicity restrictions, and combining relative magnitudes and smoothness restrictions.
```

?

**Comment by jonathandroth** [comment]
Ah, maybe that's why we were carrying this old README around. Perhaps just
link to the old version of the PDF on the github?

**Comment by mcaceresb** [comment]
@jonathandroth Like [this](https://github.com/mcaceresb/HonestDiD/tree/cran-commit-round8?tab=readme-ov-file#additional-options-and-resources)?

**Comment by jonathandroth** [comment]
Looks good to me!

**Comment by mcaceresb** [comment]
@asheshrambachan Can you try again?

**Comment by asheshrambachan** [comment]
Sorry for the delay. Just submitted the updated version to CRAN (see attached screenshot). I'll let you know what happens. 

Screenshot 2024-06-09 at 8 49 23 PM

**Comment by jonathandroth** [comment]
Thanks Ashesh!

**Comment by asheshrambachan** [comment]
Good news: HonestDiD passed all of the incoming checks! Thanks @mcaceresb for all the work to clean up the package. 

There are a few minor style comments the CRAN managers had for us -- see the screenshot below. My understanding is: since we passed the automatic incoming checks, these style points are the last hurdle to CRAN. 

Screenshot 2024-06-11 at 8 47 43 AM

**Comment by jonathandroth** [comment]
Thanks guys! This has been more work than publishing the paper in restud ...

**Comment by mcaceresb** [comment]
@asheshrambachan @jonathandroth They literally told us our examples took too long to run... I had an entire internal debate about using dontrun vs donttest and I decided to do the former to be cautious just in case, and it seems I erred on the wrong side of caution.

Anyway, made both changes.

**Comment by asheshrambachan** [comment]
Thanks @mcaceresb! Just resubmitted. Fingers crossed this time. 
Screenshot 2024-06-11 at 3 01 09 PM

**Comment by jonathandroth** [comment]
Thanks guys! Did we address the comment about setting the seed?

**Comment by mcaceresb** [comment]
@jonathandroth @asheshrambachan No, I missed it! I'm sorry. I'll see what that's about as soon as I can. Really sorry!

**Comment by jonathandroth** [comment]
No worries, and thanks!

**Comment by jonathandroth** [comment]
Ashesh, have we heard anything back from CRAN?

**Comment by asheshrambachan** [comment]
Have we converged on what to do about setting the seed per the feedback from CRAN? I see the pull request there is still open, so I have been holding off on resubmitting until that's resolved.

**Comment by jonathandroth** [comment]
@asheshrambachan I'm slightly confused because it looked like you said you resubmitted it already (before I brought up the issue with the seed)? You posted a screenshot earlier in this thread, so I was wondering if they responded to that. 

@mcaceresb -- what is the latest with handling the seed?

**Comment by asheshrambachan** [comment]
@jonathandroth Ah yup -- they flagged the same concern about the seed, and so I have not resubmitted it since then. Sorry for the miscommunication!

**Comment by jonathandroth** [comment]
No worries! Well at least it sounds like they didn't complain about anything else?

**Comment by asheshrambachan** [comment]
Correct! The package otherwise passed all checks, so (fingers crossed) once this is fixed we should be good to go.

**Comment by mcaceresb** [comment]
[This](https://github.com/asheshrambachan/HonestDiD/pull/42#issuecomment-2218483379) has been addressed after the merge from #59

@asheshrambachan @jonathandroth

**Comment by jonathandroth** [comment]
Thanks, Mauricio! @asheshrambachan you should be good to resubmit!

**Comment by asheshrambachan** [comment]
Thanks @mcaceresb! Just resubmitted the package. 

Screenshot 2024-07-11 at 5 22 58 PM

**Comment by jonathandroth** [comment]
Thanks both! Hopefully this is the last time :-)

**Comment by asheshrambachan** [comment]
Good news! Package looks to be on its way to CRAN. 

Screenshot 2024-07-14 at 10 18 39 AM

**Comment by jonathandroth** [comment]
Woohoo :)

**Pull request merged**
